apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wwww
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-app1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: website/blog-vconsultants-be
    repoURL: https://github.com/hpreyers/root-websites.git
    targetRevision: HEAD
