apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev-master-websites/blog-vconsultants-be
    repoURL: https://github.com/hpreyers/k8s-test-argocd.git
    targetRevision: HEAD
